### ISSUE TITLE
Demeter doesn't work properly when you delete the output folder for some time

### ISSUE THREAD

**Issue by CGL5230** [JGCRI/demeter#48]
Hi,all! I've run the default scenario many times recently with demeter, and this has produced a series of outputs for a range of time periods.
![Image](https://github.com/user-attachments/assets/e0d6fb8d-05ad-4736-80b5-2ffd9a1351ba)
My Question:
1.  **I deleted a few of the output folder**,like gcam5p1p3_ref_2024-10-14_02h36m12s folder. Demeter wouldn't work. **The error is that the log file for gcam5p1p3_ref_2024-10-14_02h36m12s folder cannot be found(From demeter report).**
2. Also, **I tried changing the output path** in the config file, but that doesn't seem to work. **demeter still outputs in the outputs folder**.

**Comment by kanishkan91** [comment]
Hello. Thanks for the comment. 

1. By default, the outputs should be time stamped, so deleting an output from the outputs folder should not matter. Were the file immediately deleted after a run? I think that's the only concievable scenario where it can't overwrite a scenario.
2. Regarding point number 2, this may be a bug since it seems the "output" path may be hardcoded somewhere. I can take a look at the same.

**Comment by CGL5230** [comment]
For Q1: Yes. But I I deleted the output folder,not output files. I think the Demeter reads the sequence timestreams sequentially and then creates an output folder for the most recent time.
